# Generated by Django 5.2.7 on 2025-10-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_created_at_remove_event_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinvitation',
            name='suggested_end_time',
        ),
        migrations.RemoveField(
            model_name='eventinvitation',
            name='suggested_start_time',
        ),
    ]
