# Generated by Django 5.2.7 on 2025-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventinvitation_suggested_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('family', 'Family'), ('social', 'Social'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('holiday', 'Holiday'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
