# Generated by Django 5.2.7 on 2025-10-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('family', 'Family'), ('social', 'Social'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('holiday', 'Holiday')], max_length=20, null=True),
        ),
    ]
