# Generated by Django 5.2.7 on 2025-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventinvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('private', 'Only me'), ('public', 'Everyone'), ('invited', 'Only invited users'), ('custom', 'Custom selection')], default='private', max_length=10),
        ),
    ]
