# Generated by Django 5.2.7 on 2025-10-29 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_visibility'),
        ('groups', '0002_remove_group_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_to_friends',
            field=models.ManyToManyField(blank=True, related_name='events_visibility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, related_name='events_visibility', to='groups.group'),
        ),
    ]
