# Generated by Django 5.2.7 on 2025-11-03 19:34

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_visible_to_friends_event_visible_to_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(validators=[events.models.validate_10_min_interval]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(validators=[events.models.validate_10_min_interval]),
        ),
    ]
