# Generated by Django 5.2.7 on 2025-10-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='created_at',
        ),
    ]
